/* ============================================================
   HEXON BETA — Piece skins
   ============================================================
   A "skin" is a named palette + accent colour that re-paints every
   piece, tray cell, board cell, and shop preview. Skins live in
   state.skins (equipped + unlocked) and are persisted via
   storage.js. Players unlock new skins from the in-game shop.

   This file is split into two layers:

     1. Hand-crafted "themed" skins (default, neon, aurora, …) that
        ship with bespoke 10-colour palettes and unique SVG glyphs.

     2. A procedurally-generated "RGB ingredient" family — every skin
        is described by three weights (r, g, b ∈ [0,1]) representing
        how much of each pure colour channel goes into the recipe. The
        palette is generated by varying brightness / white-mix while
        keeping the recipe ratio intact, so the skin always reads as
        "this much red + this much green + this much blue". The icon
        shows the three pure-channel drops sized by their weight plus
        the resulting mixed colour — no two recipes look the same.

   Adding a themed skin: append an entry to SKINS with a unique id,
   a name, a price in HEX coins, and a 6+ colour palette. Adding an
   RGB recipe skin: append a descriptor to RGB_RECIPE_SKINS and the
   factory below will mint the palette + icon automatically.
   ============================================================ */
"use strict";

const SKINS = {
  default: {
    name: "Класична",
    price: 0,
    accent: "#7c5cff",
    palette: [
      "#7c5cff","#24bdff","#3ddc97","#ffb454","#ff6470",
      "#a766ff","#22d3ee","#facc15","#f472b6","#34d399",
    ],
  },
  neon: {
    name: "Неон",
    price: 800,
    accent: "#39ff14",
    palette: [
      "#39ff14","#ff00ff","#00ffff","#ffea00","#ff3df0",
      "#7cff8a","#5cffff","#fff04d","#ff6dff","#a3ff5c",
    ],
  },
  aurora: {
    name: "Аврора",
    price: 1500,
    accent: "#7CF1B8",
    palette: [
      "#7cf1b8","#6cc9ff","#a98bff","#ffd1f0","#6affd3",
      "#92d8ff","#c2a4ff","#ffb6e9","#73f3c5","#88c8ff",
    ],
  },
  ocean: {
    name: "Океан",
    price: 2500,
    accent: "#1097d6",
    palette: [
      "#1097d6","#0ec8b6","#2c5fbf","#7cd9ff","#3ddc97",
      "#1a5fa3","#0fbfd4","#5bb1ff","#23b8a1","#3a7cd8",
    ],
  },
  sunset: {
    name: "Захід",
    price: 5000,
    accent: "#ff7a59",
    palette: [
      "#ff7a59","#ffb454","#ff5e9e","#ffd166","#ef476f",
      "#ff8e5e","#ffc06b","#ff77b2","#ffd884","#f55a85",
    ],
  },
  pastel: {
    name: "Пастель",
    price: 3000,
    accent: "#fcb1e5",
    palette: [
      "#fcb1e5","#b1d6fc","#c7fcb1","#fcd6b1","#d6b1fc",
      "#fcc6c6","#b1f0fc","#e7fcb1","#fce0b1","#cab1fc",
    ],
  },
  ember: {
    name: "Жар",
    price: 8000,
    accent: "#ff3d00",
    palette: [
      "#ff3d00","#ff7300","#ffb300","#ffd000","#c41e3a",
      "#ff5722","#ff9a3a","#ffc23a","#ffea3a","#e63a4d",
    ],
  },
  galaxy: {
    name: "Галактика",
    price: 12000,
    accent: "#9b5cff",
    palette: [
      "#9b5cff","#4a3aff","#ff5cff","#5cf6ff","#ffd166",
      "#7d3aff","#3a4bff","#e74cff","#3acaff","#ffe9a3",
    ],
  },
  mono: {
    name: "Моно",
    price: 1000,
    accent: "#e6e9f5",
    palette: [
      "#e6e9f5","#bcc1d6","#9aa0b8","#7a8099","#5d6280",
      "#cad0e3","#a8aec8","#888fac","#6d7390","#4f5470",
    ],
  },
};

/* ============================================================
   RGB-ingredient skin factory
   ============================================================
   Every entry in RGB_RECIPE_SKINS is a tiny descriptor:

     { id, name, price, r, g, b }

   `r`, `g`, `b` ∈ [0,1] are the "recipe" weights — how much of each
   pure channel ends up in the result. The factory below turns that
   into a 10-colour palette by:

     - using the recipe colour at full brightness as the headline
       swatch,
     - dimming it to 70 %, 55 % and 40 % to give darker shades,
     - and adding white-mix variants (+25, +60, +100 per channel,
       clamped at 255) for the lighter tints.

   The accent (used for HUD glow, CTAs, etc.) is the headline swatch.
   ============================================================ */

/* Clamp + format a 0..255 integer as a two-char hex byte. */
function _rgbByte(n){
  const v = Math.max(0, Math.min(255, Math.round(n)));
  const s = v.toString(16);
  return s.length < 2 ? "0" + s : s;
}
/* Pack three 0..255 channels into a #rrggbb literal. */
function _rgbHex(r, g, b){
  return "#" + _rgbByte(r) + _rgbByte(g) + _rgbByte(b);
}
/* Single palette entry: scale the recipe by `factor`, then add a
   flat `white` value to every channel (for tints). Both knobs are
   clamped at 0..255 by _rgbByte. */
function _rgbMix(base, factor, white){
  return _rgbHex(
    base[0] * factor + white,
    base[1] * factor + white,
    base[2] * factor + white,
  );
}
/* Build the 10-colour palette for an (r,g,b) recipe. The order is
   tuned so the first 6 entries (which the shop swatch shows) hit a
   nice spread of dim/bright/tinted variations. */
function _makeRgbPalette(r, g, b){
  const base = [r * 255, g * 255, b * 255];
  return [
    _rgbMix(base, 1.00,   0),  // headline
    _rgbMix(base, 0.70,   0),  // dim
    _rgbMix(base, 1.00,  60),  // tint
    _rgbMix(base, 0.85,  25),  // bright dim
    _rgbMix(base, 0.55,   0),  // dark
    _rgbMix(base, 1.00, 100),  // pale tint
    _rgbMix(base, 0.92,   0),  // slight dim
    _rgbMix(base, 0.40,   0),  // very dark
    _rgbMix(base, 0.95,  40),  // medium tint
    _rgbMix(base, 1.00,  30),  // bright with hint
  ];
}

/* The descriptors. Sorted by recipe family — single pure channels,
   then duo mixes (R+G, R+B, G+B), then trio mixes with one or more
   dominant channels. Prices scale with how exotic the recipe feels
   relative to the single-channel reference. */
const RGB_RECIPE_SKINS = [
  /* ---- single channels (clean R, G, B) ---- */
  { id: "rgb-red-pure",     name: "Чистий Червоний",   price: 600,  r: 1.00, g: 0.00, b: 0.00 },
  { id: "rgb-green-pure",   name: "Чистий Зелений",    price: 600,  r: 0.00, g: 1.00, b: 0.00 },
  { id: "rgb-blue-pure",    name: "Чистий Синій",      price: 600,  r: 0.00, g: 0.00, b: 1.00 },
  { id: "rgb-red-deep",     name: "Глибокий Червоний", price: 700,  r: 0.65, g: 0.05, b: 0.05 },
  { id: "rgb-green-forest", name: "Лісовий Зелений",   price: 700,  r: 0.05, g: 0.65, b: 0.10 },
  { id: "rgb-blue-deep",    name: "Глибокий Синій",    price: 700,  r: 0.05, g: 0.10, b: 0.70 },

  /* ---- R+G family (yellows, oranges, limes) ---- */
  { id: "rgb-yellow",       name: "Жовтий",            price: 1200, r: 1.00, g: 1.00, b: 0.00 },
  { id: "rgb-amber",        name: "Бурштин",           price: 1300, r: 1.00, g: 0.60, b: 0.00 },
  { id: "rgb-orange",       name: "Помаранч",          price: 1400, r: 1.00, g: 0.40, b: 0.00 },
  { id: "rgb-lime",         name: "Лайм",              price: 1300, r: 0.60, g: 1.00, b: 0.00 },
  { id: "rgb-gold",         name: "Золото",            price: 1700, r: 1.00, g: 0.84, b: 0.20 },
  { id: "rgb-pumpkin",      name: "Гарбуз",            price: 1500, r: 1.00, g: 0.55, b: 0.10 },
  { id: "rgb-sunflower",    name: "Соняшник",          price: 1500, r: 1.00, g: 0.95, b: 0.10 },
  { id: "rgb-copper",       name: "Мідь",              price: 1600, r: 0.90, g: 0.50, b: 0.20 },

  /* ---- R+B family (magentas, pinks, violets) ---- */
  { id: "rgb-magenta",      name: "Маджента",          price: 1400, r: 1.00, g: 0.00, b: 1.00 },
  { id: "rgb-pink",         name: "Рожевий",           price: 1300, r: 1.00, g: 0.20, b: 0.60 },
  { id: "rgb-violet",       name: "Фіалка",            price: 1500, r: 0.60, g: 0.00, b: 1.00 },
  { id: "rgb-rose",         name: "Троянда",           price: 1400, r: 1.00, g: 0.30, b: 0.50 },
  { id: "rgb-fuchsia",      name: "Фуксія",            price: 1700, r: 1.00, g: 0.10, b: 0.70 },
  { id: "rgb-plum",         name: "Слива",             price: 1500, r: 0.55, g: 0.10, b: 0.55 },
  { id: "rgb-bubblegum",    name: "Жуйка",             price: 1500, r: 1.00, g: 0.55, b: 0.85 },

  /* ---- G+B family (cyans, teals, aquas) ---- */
  { id: "rgb-cyan",         name: "Циан",              price: 1400, r: 0.00, g: 1.00, b: 1.00 },
  { id: "rgb-teal",         name: "Бірюза",            price: 1300, r: 0.05, g: 0.70, b: 0.70 },
  { id: "rgb-aqua",         name: "Аква",              price: 1400, r: 0.05, g: 1.00, b: 0.75 },
  { id: "rgb-mint",         name: "М'ята",             price: 1400, r: 0.30, g: 1.00, b: 0.65 },
  { id: "rgb-turquoise",    name: "Туркіз",            price: 1700, r: 0.20, g: 0.85, b: 0.75 },
  { id: "rgb-seafoam",      name: "Морська піна",      price: 1600, r: 0.50, g: 0.95, b: 0.75 },
  { id: "rgb-electric",     name: "Електрика",         price: 1700, r: 0.25, g: 0.95, b: 1.00 },

  /* ---- red-dominant trios ---- */
  { id: "rgb-coral",        name: "Корал",             price: 2400, r: 1.00, g: 0.55, b: 0.40 },
  { id: "rgb-salmon",       name: "Лосось",            price: 2200, r: 1.00, g: 0.50, b: 0.35 },
  { id: "rgb-rust",         name: "Іржа",              price: 2500, r: 0.80, g: 0.30, b: 0.10 },
  { id: "rgb-brick",        name: "Цегла",             price: 2400, r: 0.70, g: 0.25, b: 0.25 },
  { id: "rgb-wine",         name: "Вино",              price: 2800, r: 0.50, g: 0.10, b: 0.20 },
  { id: "rgb-peach",        name: "Персик",            price: 2000, r: 1.00, g: 0.80, b: 0.70 },
  { id: "rgb-mocha",        name: "Мокка",             price: 2300, r: 0.60, g: 0.40, b: 0.30 },

  /* ---- green-dominant trios ---- */
  { id: "rgb-emerald",      name: "Смарагд",           price: 2800, r: 0.10, g: 0.80, b: 0.35 },
  { id: "rgb-jade",         name: "Нефрит",            price: 2600, r: 0.25, g: 0.70, b: 0.50 },
  { id: "rgb-olive",        name: "Олива",             price: 2300, r: 0.55, g: 0.60, b: 0.15 },
  { id: "rgb-spring",       name: "Весна",             price: 2300, r: 0.45, g: 1.00, b: 0.45 },
  { id: "rgb-moss",         name: "Мох",               price: 2200, r: 0.40, g: 0.55, b: 0.25 },
  { id: "rgb-mint-cream",   name: "М'ятний крем",      price: 2100, r: 0.70, g: 0.95, b: 0.85 },

  /* ---- blue-dominant trios ---- */
  { id: "rgb-sapphire",     name: "Сапфір",            price: 3000, r: 0.10, g: 0.30, b: 0.90 },
  { id: "rgb-cobalt",       name: "Кобальт",           price: 2800, r: 0.10, g: 0.20, b: 0.80 },
  { id: "rgb-azure",        name: "Азур",              price: 2400, r: 0.20, g: 0.60, b: 1.00 },
  { id: "rgb-ice",          name: "Лід",               price: 2200, r: 0.75, g: 0.92, b: 1.00 },
  { id: "rgb-frost",        name: "Іній",              price: 2200, r: 0.65, g: 0.85, b: 1.00 },
  { id: "rgb-ocean-deep",   name: "Глибина",           price: 2700, r: 0.05, g: 0.30, b: 0.60 },
  { id: "rgb-lavender",     name: "Лаванда",           price: 2300, r: 0.70, g: 0.55, b: 0.95 },

  /* ---- balanced trios (greys, whites, sands) ---- */
  { id: "rgb-white",        name: "Білий",             price: 900,  r: 1.00, g: 1.00, b: 1.00 },
  { id: "rgb-grey",         name: "Сірий",             price: 800,  r: 0.60, g: 0.60, b: 0.60 },
  { id: "rgb-stone",        name: "Камінь",            price: 1100, r: 0.55, g: 0.50, b: 0.45 },
  { id: "rgb-graphite",     name: "Графіт",            price: 1300, r: 0.30, g: 0.32, b: 0.36 },
  { id: "rgb-cool",         name: "Прохолода",         price: 1600, r: 0.70, g: 0.75, b: 1.00 },
  { id: "rgb-warm",         name: "Тепло",             price: 1600, r: 1.00, g: 0.80, b: 0.60 },
  { id: "rgb-sand",         name: "Пісок",             price: 1500, r: 0.92, g: 0.80, b: 0.50 },
  { id: "rgb-prism",        name: "Призма",            price: 3500, r: 0.90, g: 0.75, b: 0.95 },
];

/* Mint each descriptor into a full SKINS entry. The factory only
   runs once at module load, so the cost is paid before the first
   render. */
RGB_RECIPE_SKINS.forEach(rec => {
  const palette = _makeRgbPalette(rec.r, rec.g, rec.b);
  SKINS[rec.id] = {
    name:    rec.name,
    price:   rec.price | 0,
    accent:  palette[0],
    palette: palette,
    /* Stash the recipe so the icon builder below can read it back
       without re-parsing the palette. */
    rgb:     { r: rec.r, g: rec.g, b: rec.b },
  };
});

/* ============================================================
   Per-skin icons
   ============================================================
   Each themed skin has a unique hand-drawn SVG glyph that fills with
   three colours pulled from its own palette. RGB-recipe skins fall
   through to a parameterized "ingredient drops" builder that draws
   pure R/G/B circles sized by the recipe weights, with the resulting
   mixed colour as the central dot. Two different recipes always look
   different at a glance.
   ============================================================ */
const SKIN_ICON_BUILDERS = {
  /* Three nested hexagons in the palette's primary, secondary and
     tertiary colours — a literal "stack of pieces" emblem. */
  default: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="M12 2 L20 7 L20 17 L12 22 L4 17 L4 7 Z" fill="' + p[0] + '" opacity="0.85"/>' +
      '<path d="M12 6 L17 9 L17 15 L12 18 L7 15 L7 9 Z" fill="' + p[1] + '"/>' +
      '<path d="M12 10 L14 11 L14 13 L12 14 L10 13 L10 11 Z" fill="' + p[2] + '"/>' +
    '</svg>'
  ),
  /* A lightning bolt with a faint after-glow trail — neon arcade
     vibes that match the harsh palette. */
  neon: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="M14 2 L4 14 H10 L8 22 L20 10 H14 L15 2 Z" fill="' + p[2] + '" opacity="0.45"/>' +
      '<path d="M13 2 L3 14 H9 L7 22 L19 10 H13 L14 2 Z" fill="' + p[0] + '"/>' +
      '<circle cx="20" cy="4"  r="1.4" fill="' + p[1] + '"/>' +
      '<circle cx="4"  cy="20" r="1.0" fill="' + p[1] + '"/>' +
    '</svg>'
  ),
  /* Three horizontal wave bands — the actual northern-lights look. */
  aurora: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" stroke-linecap="round" stroke-width="3">' +
      '<path d="M2 7 C 6 3, 10 11, 14 7 S 22 3, 22 7" stroke="' + p[0] + '"/>' +
      '<path d="M2 13 C 6 9, 10 17, 14 13 S 22 9, 22 13" stroke="' + p[1] + '"/>' +
      '<path d="M2 19 C 6 15, 10 23, 14 19 S 22 15, 22 19" stroke="' + p[2] + '"/>' +
    '</svg>'
  ),
  /* Sea swell with a single droplet over it — calm-water motif. */
  ocean: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="M2 14 C 6 11, 9 17, 12 14 S 18 11, 22 14 V22 H2 Z" fill="' + p[0] + '"/>' +
      '<path d="M2 18 C 6 15, 9 21, 12 18 S 18 15, 22 18 V22 H2 Z" fill="' + p[1] + '" opacity="0.9"/>' +
      '<path d="M17 3 C 19 6, 20 8, 17 8 S 15 6, 17 3 Z" fill="' + p[2] + '"/>' +
    '</svg>'
  ),
  /* Half-disc sun rising over a horizon, with a single hot ray. */
  sunset: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<circle cx="12" cy="14" r="7" fill="' + p[0] + '"/>' +
      '<circle cx="12" cy="14" r="4" fill="' + p[3] + '" opacity="0.85"/>' +
      '<rect x="0" y="16" width="24" height="3"  fill="' + p[1] + '" opacity="0.55"/>' +
      '<rect x="0" y="20" width="24" height="2"  fill="' + p[2] + '" opacity="0.75"/>' +
      '<path d="M12 2 V6 M6 6 L8 8 M18 6 L16 8" stroke="' + p[3] + '" stroke-width="1.6" stroke-linecap="round"/>' +
    '</svg>'
  ),
  /* Three overlapping clouds in soft pastel hues. */
  pastel: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<circle cx="8"  cy="11" r="5" fill="' + p[0] + '"/>' +
      '<circle cx="15" cy="13" r="6" fill="' + p[1] + '" opacity="0.92"/>' +
      '<circle cx="11" cy="16" r="3" fill="' + p[2] + '"/>' +
      '<circle cx="18" cy="7"  r="1.6" fill="' + p[3] + '"/>' +
    '</svg>'
  ),
  /* Twin-tongue flame, hot core + cooler outer layer. */
  ember: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="M12 2 C 14 5, 17 7, 17 12 a5 5 0 1 1 -10 0 c 0 -3 2 -4 3 -6 -1 4 2 6 2 6 s -2 -3 0 -10 Z" fill="' + p[0] + '"/>' +
      '<path d="M12 9 C 13 11, 15 12, 15 15 a3 3 0 1 1 -6 0 c 0 -2 2 -2 3 -4 -1 3 2 3 2 3 s -2 -2 0 -1 Z" fill="' + p[2] + '"/>' +
      '<circle cx="12" cy="17" r="2" fill="' + p[3] + '"/>' +
    '</svg>'
  ),
  /* Tilted ellipse orbit with a coloured planet + scattered stars. */
  galaxy: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<g transform="rotate(-22 12 12)">' +
        '<ellipse cx="12" cy="12" rx="10" ry="3.5" fill="none" stroke="' + p[0] + '" stroke-width="1.6" opacity="0.85"/>' +
      '</g>' +
      '<circle cx="12" cy="12" r="3.6" fill="' + p[1] + '"/>' +
      '<circle cx="12" cy="12" r="1.8" fill="' + p[2] + '"/>' +
      '<path d="M5  4 L5.6 5.4 L7 6 L5.6 6.6 L5 8 L4.4 6.6 L3 6 L4.4 5.4 Z" fill="' + p[3] + '"/>' +
      '<path d="M19 18 L19.5 19 L20.5 19.5 L19.5 20 L19 21 L18.5 20 L17.5 19.5 L18.5 19 Z" fill="' + p[4] + '"/>' +
    '</svg>'
  ),
  /* Faceted diamond / gem — all four facets carved from the same
     monochrome palette to highlight the "shades of grey" theme. */
  mono: (p) => (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      '<path d="M12 3 L21 9 L12 22 L3 9 Z" fill="' + p[0] + '"/>' +
      '<path d="M12 3 L21 9 L12 13 Z" fill="' + p[3] + '" opacity="0.9"/>' +
      '<path d="M12 3 L3 9 L12 13 Z" fill="' + p[1] + '" opacity="0.92"/>' +
      '<path d="M12 13 L21 9 L12 22 Z" fill="' + p[2] + '" opacity="0.92"/>' +
    '</svg>'
  ),
};

/* Default builder for any RGB-recipe skin. Draws three pure-channel
   drops sized by the recipe weights — pure red top-left, pure green
   top-right, pure blue bottom — overlapping in the middle. A small
   centre dot shows the actual resulting colour from the skin's
   palette so the player can match icon → swatch at a glance. Drops
   whose weight is essentially zero are skipped so a "pure red" recipe
   shows just the red drop instead of three tiny dots. */
function _rgbRecipeIcon(skin){
  const rec = skin && skin.rgb;
  if(!rec) return SKIN_ICON_BUILDERS.default(skin.palette);
  /* Drop sizes scale linearly with weight, but clamp at a minimum
     visible radius so even a 5 % ingredient still reads. */
  const dropRadius = (w) => 2.4 + Math.max(0, Math.min(1, w)) * 4.6;
  const dropOpacity = (w) => 0.45 + Math.max(0, Math.min(1, w)) * 0.45;
  /* The three "ingredient" pots sit at the corners of a triangle;
     they overlap in the middle so additive mixing reads visually. */
  const drops = [];
  if(rec.r > 0.03) drops.push(
    '<circle cx="8"  cy="9"  r="' + dropRadius(rec.r).toFixed(2) +
    '" fill="#ff1f3a" opacity="' + dropOpacity(rec.r).toFixed(2) + '"/>'
  );
  if(rec.g > 0.03) drops.push(
    '<circle cx="16" cy="9"  r="' + dropRadius(rec.g).toFixed(2) +
    '" fill="#21d96a" opacity="' + dropOpacity(rec.g).toFixed(2) + '"/>'
  );
  if(rec.b > 0.03) drops.push(
    '<circle cx="12" cy="17" r="' + dropRadius(rec.b).toFixed(2) +
    '" fill="#3a8fff" opacity="' + dropOpacity(rec.b).toFixed(2) + '"/>'
  );
  /* The mixed-result dot — uses the skin's own headline colour so it
     looks like the "output" of the three ingredients. A thin white
     ring lifts it off the overlapping drops. */
  const result = (skin.palette && skin.palette[0]) || "#888";
  return (
    '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
      drops.join("") +
      '<circle cx="12" cy="12" r="2.4" fill="' + result + '" stroke="rgba(255,255,255,.7)" stroke-width="0.7"/>' +
    '</svg>'
  );
}

/* Build the icon SVG string for a skin. Returns "" if the id is
   unknown so callers can do `if (svg) container.innerHTML = svg;`. */
function skinIconSvg(id){
  const skin = SKINS[id];
  if(!skin) return "";
  const build = SKIN_ICON_BUILDERS[id];
  if(build) return build(skin.palette);
  if(skin.rgb) return _rgbRecipeIcon(skin);
  return SKIN_ICON_BUILDERS.default(skin.palette);
}

/* The list order used by the shop grid. Default comes first so the
   player always sees the "equipped" pill at the top, then the
   hand-crafted themed skins, then every RGB-recipe skin in the order
   they were declared. */
const SHOP_SKIN_ORDER = [
  "default","neon","aurora","ocean","pastel","sunset","ember","galaxy","mono",
].concat(RGB_RECIPE_SKINS.map(r => r.id));

function currentSkinId(){
  return (state.skins && state.skins.equipped) || "default";
}
function currentSkin(){
  return SKINS[currentSkinId()] || SKINS.default;
}
function currentPalette(){
  return currentSkin().palette;
}
function isSkinUnlocked(id){
  return !!(state.skins && Array.isArray(state.skins.unlocked) && state.skins.unlocked.indexOf(id) >= 0);
}
function unlockSkin(id){
  if(!SKINS[id]) return false;
  if(!state.skins) state.skins = { equipped:"default", unlocked:["default"] };
  if(!Array.isArray(state.skins.unlocked)) state.skins.unlocked = ["default"];
  if(state.skins.unlocked.indexOf(id) < 0) state.skins.unlocked.push(id);
  return true;
}
function equipSkin(id){
  if(!SKINS[id]) return false;
  if(!isSkinUnlocked(id)) return false;
  state.skins.equipped = id;
  applySkinAccent();
  return true;
}
/* Push the equipped skin's accent into a CSS custom property so the
   menu, HUD, and shop can tint themselves to match the current
   piece palette without re-reading the JS state. */
function applySkinAccent(){
  const s = currentSkin();
  document.documentElement.style.setProperty("--skin-accent", s.accent || "#7c5cff");
}
